project:
  type: website
  output-dir: docs

website:
  title: "HKIWebsite"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - href: https://github.com/H-unter
        icon: fab fa-github
        text: GitHub
    logo: elements/switchswirl.jpg
  sidebar:
    style: docked
    search: true
    contents:
      - section: "Tools"
      - contents: 
          - page1.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



